# -*- coding: utf-8 -*-
"""deplyment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zSZ59BQUiXRqe3yHK3rDSdveRS8wGXb6

# load the weights
"""

import pickle
my_model = pickle.load(open('/content/startup_weights (1).sav', 'rb'))

"""# load the scaler file"""

import joblib
x_scale = joblib.load('/content/Xscaler.save') 
y_scale = joblib.load('/content/yscaler.save')

"""# take input from user"""

r_d = float(input('enter the money you will spend on R&D '))
AD = float(input('enter the money you will spend on AD '))
M = float(input('enter the money you will spend on Maerketing '))
florida = int(input( '0 or 1'))
new_york = int(input( '0 or 1'))

inputs = [[r_d, AD, M, florida, new_york]]

inputs = x_scale.transform(inputs)

print(inputs)

output = my_model.predict(inputs)

output = y_scale.inverse_transform(output)

output